### ISSUE TITLE
Inspiration for more complete support

### ISSUE THREAD

**Issue by petterreinholdtsen** [MoveOnOrg/django-odata#2]
Hi. The README state that several features are not implemented yet.  Perhaps some inspiration can be found from https://github.com/tiagobalmeida/django-odata/ on some of the remaining parts?

**Comment by schuyler1d** [comment]
That repo is completely empty and only has a license and readme file (i.e. no code).

This project is not in active development, but we'll accept pull requests if you want to add more support.

**Comment by petterreinholdtsen** [comment]
[Schuyler Duveen]
> That repo is completely empty and only has a license and readme file
> (i.e. no code).

The code is in the 'dev' branch.  I suspect you only looked at the
'master' branch.

-- 
Happy hacking
Petter Reinholdtsen
